## Code to test strategies for LTC self-insurance
- [X] Import history of key funds/indexes: S&P 500, DJIA, Money Market
- [X] Build Simulation based on random date forward
- [O] Build Simulation based on Joint Distribution of Index and Money Market
- [O] Build Simulation using 90/10 or 85/15 strategy 
- [O] 
- [O]

In [2]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time,  datetime
from datetime import date
from ta.momentum import RSIIndicator
import yfinance as yf
import os.path
from fredapi import Fred
import math
import trader_functions as tf
import yaml

with open('fred_api.yaml', 'r') as file:
    configs = yaml.safe_load(file)

fred_api_key = configs['fred_api']

In [3]:
def get_prices(ticker, start="1999-01-01", end=None, printname=False):
    """
    Given a stock ticker, this function uses the yfinance API to pull prices.
    Optionally prints the company long name using get_info().
    """

    if end is None:
        end = datetime.date.today().strftime("%Y-%m-%d")

    # Print company name safely
    if printname and isinstance(ticker, str):
        try:
            compdata = yf.Ticker(ticker)
            info = compdata.get_info()
            company_name = info.get("longName", "Name not available")
            print(f"Getting {ticker}: {company_name}")
        except Exception as e:
            print(f"Getting {ticker}: (Name unavailable)")

    try:
        prices = yf.download(
            ticker, start=start, end=end, progress=False, interval="1mo"
        )

        if prices.empty:
            raise ValueError("No price data returned.")

        # Handle MultiIndex safely
        if isinstance(prices.columns, pd.MultiIndex):
            prices = prices["Close"]
        else:
            prices = prices["Close"]

        return prices

    except Exception as e:
        print(f"Error retrieving price data for {ticker}: {e}")
        return None

In [4]:
start_date = "1929-01-01"
start_date = "1947-01-01"
end_date = datetime.date.today().strftime("%Y-%m-%d")

indexes = {
    # "^DJI": "Dow Jones Industrial Average",
    "^GSPC": "Standard & Poors 500",
    # "^IRX": "13-week Treasury Bill yield",
    # "^IXIC": "NASDAQ Composite,",
    # "^RUT": "Russell 2000 Index",
    # "^CPI": "Comsumer Price Index",
}
tickers = list(indexes.keys())
# df = yf.download(tickers, start=start_date, end=end_date, interval='1mo')

prices = yf.download(tickers, start=start_date, end=end_date, interval="1d")["Close"]
# prices = yf.download("^GSPC", start="1929-01-01", interval="1d")

# Convert to monthly (end-of-month)
prices = prices.resample("MS").first()
prices.head()

[*********************100%***********************]  1 of 1 completed

Ticker      ^GSPC
Date
1947-01-01  15.20
1947-02-01  15.80
1947-03-01  15.41
1947-04-01  15.23
1947-05-01  14.69

In [6]:
fred = Fred(api_key=fred_api_key)
cpi = fred.get_series("CPIAUCSL")
cpi.head()

1947-01-01    21.48
1947-02-01    21.62
1947-03-01    22.00
1947-04-01    22.00
1947-05-01    21.95
dtype: float64

In [7]:
pricesi = prices.merge(cpi.rename("cpi"), left_index=True, right_index=True)
pricesi.tail()

                  ^GSPC      cpi
2025-11-01  6851.970215  325.063
2025-12-01  6812.629883  326.031
2026-01-01  6858.470215  326.588
2026-02-01  6976.439941  327.460
2026-03-01  6881.620117  330.293

In [9]:
tmp = pricesi.reset_index()
tmp.rename(columns={"index": "month"}, inplace=True)

arrayi = tmp.to_records()
arrayi[0:3]

rec.array([(0, '1947-01-01T00:00:00.000000000', 15.19999981, 21.48),
           (1, '1947-02-01T00:00:00.000000000', 15.80000019, 21.62),
           (2, '1947-03-01T00:00:00.000000000', 15.40999985, 22.  )],
          dtype=[('index', '<i8'), ('month', '<M8[ns]'), ('^GSPC', '<f8'), ('cpi', '<f8')])

#### Test the process in open code

In [10]:
starting_balance = 300_000.0  # $300k
time_til_event = 20 * 12  # 20 years (mike is 73)
duration_of_event = 5 * 12  # 5 years
start_index = 0
index_used = "^GSPC"
monthly_care_amount = 10_000.0  # Using a fixed amount for now
tax_rate = 0.25

# Ages at beginning
ti, mike = 54, 53

balance_at_event = (
    starting_balance
    * arrayi[start_index + time_til_event][index_used]
    / arrayi[start_index][index_used]
)
start_date = arrayi[start_index]["month"].astype("datetime64[D]")
event_date = arrayi[start_index + time_til_event]["month"].astype("datetime64[D]")
sb = "${:,.2f}".format(starting_balance)

print(f"Simulation begins on {start_date}, with initial investment of {sb}")
print(f"Event occurs on {event_date}")
print("Amount at event ${:,.2f}".format(balance_at_event))
print(f"Ages at event: Ti {ti+time_til_event/12}, Mike {mike+time_til_event/12}")

Simulation begins on 1947-01-01, with initial investment of $300,000.00
Event occurs on 1967-01-01
Amount at event $1,586,447.33
Ages at event: Ti 74.0, Mike 73.0

In [11]:
# Loop through months to manage payments
balance = balance_at_event
cum_spend, cum_withdraw, cum_tax = 0, 0, 0
out_df = pd.DataFrame(
    {
        "index": [time_til_event],
        "month": [event_date],
        "balance": [balance],
        "cum_spend": [cum_spend],
        "cum_withdraw": [cum_withdraw],
        "cum_tax": [cum_tax],
        "monthly_return(%)": [0.0],
    }
)


for m in range(time_til_event, time_til_event + duration_of_event + 1):
    # for m in range(time_til_event, time_til_event + 24 + 1):
    date = arrayi[m]["month"].astype("datetime64[D]")
    # spend = monthly_care_amount
    spend = monthly_care_amount * (arrayi[m]["cpi"] / arrayi[start_index]["cpi"])
    tax = monthly_care_amount * tax_rate
    withdraw = spend + tax

    cum_spend += spend
    cum_withdraw += withdraw
    cum_tax += tax

    balance -= withdraw
    monthly_return = arrayi[m][index_used] / arrayi[m - 1][index_used]
    balance = balance * monthly_return
    fbalance = "${:,.2f}".format(balance)
    formatted = [f"{x:,.2f}" for x in [balance, cum_spend, cum_withdraw, cum_tax]]

    print(m, date, formatted)

    new_row = {
        "index": m + 1,
        "month": date,
        "balance": balance,
        "cum_spend": cum_spend,
        "cum_withdraw": cum_withdraw,
        "cum_tax": cum_tax,
        "monthly_return(%)": 100 * (monthly_return - 1),
    }
    out_df.loc[len(out_df)] = new_row
    # print(m, date, fbalance, f"${cum_spend:,.2f}", cum_withdraw, cum_tax, f"{monthly_return:,.2f}",  "{:,.4f}".format(monthly_return-1))

240 1967-01-01 ['1,574,507.16', '15,316.57', '17,816.57', '2,500.00']
241 1967-02-01 ['1,673,808.77', '30,679.70', '35,679.70', '5,000.00']
242 1967-03-01 ['1,679,894.87', '46,042.83', '53,542.83', '7,500.00']
243 1967-04-01 ['1,691,555.13', '61,452.51', '71,452.51', '10,000.00']
244 1967-05-01 ['1,759,915.81', '76,862.20', '89,362.20', '12,500.00']
245 1967-06-01 ['1,674,902.21', '92,364.99', '107,364.99', '15,000.00']
246 1967-07-01 ['1,669,339.40', '107,914.34', '125,414.34', '17,500.00']
247 1967-08-01 ['1,732,252.67', '123,510.24', '143,510.24', '20,000.00']
248 1967-09-01 ['1,683,735.35', '139,152.70', '161,652.70', '22,500.00']
249 1967-10-01 ['1,712,483.16', '154,841.71', '179,841.71', '25,000.00']
250 1967-11-01 ['1,630,703.67', '170,623.84', '198,123.84', '27,500.00']
251 1967-12-01 ['1,643,505.96', '186,452.51', '216,452.51', '30,000.00']
252 1968-01-01 ['1,652,818.15', '202,327.75', '234,827.75', '32,500.00']
253 1968-02-01 ['1,574,026.87', '218,249.53', '253,249.53', '35,000.00']
254 1968-03-01 ['1,497,578.06', '234,217.88', '271,717.88', '37,500.00']
255 1968-04-01 ['1,534,999.05', '250,232.77', '290,232.77', '40,000.00']
256 1968-05-01 ['1,606,459.64', '266,294.23', '308,794.23', '42,500.00']
257 1968-06-01 ['1,620,543.27', '282,448.79', '327,448.79', '45,000.00']
258 1968-07-01 ['1,592,344.12', '298,696.46', '346,196.46', '47,500.00']
259 1968-08-01 ['1,539,989.23', '314,990.69', '364,990.69', '50,000.00']
260 1968-09-01 ['1,553,047.55', '331,331.47', '383,831.47', '52,500.00']
261 1968-10-01 ['1,588,793.11', '347,765.36', '402,765.36', '55,000.00']
262 1968-11-01 ['1,572,864.95', '364,245.81', '421,745.81', '57,500.00']
263 1968-12-01 ['1,630,078.92', '380,819.37', '440,819.37', '60,000.00']
264 1969-01-01 ['1,548,528.90', '397,439.48', '459,939.48', '62,500.00']
265 1969-02-01 ['1,514,058.30', '414,106.15', '479,106.15', '65,000.00']
266 1969-03-01 ['1,429,232.14', '430,912.48', '498,412.48', '67,500.00']
267 1969-04-01 ['1,453,397.38', '447,811.92', '517,811.92', '70,000.00']
268 1969-05-01 ['1,463,501.41', '464,757.91', '537,257.91', '72,500.00']
269 1969-06-01 ['1,436,010.82', '481,797.02', '556,797.02', '75,000.00']
270 1969-07-01 ['1,349,508.58', '498,929.24', '576,429.24', '77,500.00']
271 1969-08-01 ['1,267,324.55', '516,108.01', '596,108.01', '80,000.00']
272 1969-09-01 ['1,275,181.14', '533,379.89', '615,879.89', '82,500.00']
273 1969-10-01 ['1,215,635.81', '550,744.88', '635,744.88', '85,000.00']
274 1969-11-01 ['1,255,513.35', '568,202.98', '655,702.98', '87,500.00']
275 1969-12-01 ['1,185,484.10', '585,754.19', '675,754.19', '90,000.00']
276 1970-01-01 ['1,162,589.55', '603,398.51', '695,898.51', '92,500.00']
277 1970-02-01 ['1,053,297.79', '621,135.94', '716,135.94', '95,000.00']
278 1970-03-01 ['1,080,670.45', '638,966.48', '736,466.48', '97,500.00']
279 1970-04-01 ['1,064,501.50', '656,890.13', '756,890.13', '100,000.00']
280 1970-05-01 ['943,998.13', '674,860.34', '777,360.34', '102,500.00']
281 1970-06-01 ['882,614.94', '692,923.65', '797,923.65', '105,000.00']
282 1970-07-01 ['807,742.23', '711,033.52', '818,533.52', '107,500.00']
283 1970-08-01 ['831,112.47', '729,189.94', '839,189.94', '110,000.00']
284 1970-09-01 ['851,712.29', '747,439.48', '859,939.48', '112,500.00']
285 1970-10-01 ['865,459.30', '765,782.12', '880,782.12', '115,000.00']
286 1970-11-01 ['836,410.86', '784,217.88', '901,717.88', '117,500.00']
287 1970-12-01 ['854,046.97', '802,746.74', '922,746.74', '120,000.00']
288 1971-01-01 ['868,015.97', '821,322.16', '943,822.16', '122,500.00']
289 1971-02-01 ['895,907.90', '839,897.58', '964,897.58', '125,000.00']
290 1971-03-01 ['880,048.09', '858,519.55', '986,019.55', '127,500.00']
291 1971-04-01 ['888,896.06', '877,188.08', '1,007,188.08', '130,000.00']
292 1971-05-01 ['892,698.09', '895,949.72', '1,028,449.72', '132,500.00']
293 1971-06-01 ['845,276.40', '914,804.47', '1,049,804.47', '135,000.00']
294 1971-07-01 ['820,421.74', '933,705.77', '1,071,205.77', '137,500.00']
295 1971-08-01 ['768,385.79', '952,653.63', '1,092,653.63', '140,000.00']
296 1971-09-01 ['771,097.63', '971,648.04', '1,114,148.04', '142,500.00']
297 1971-10-01 ['748,497.44', '990,689.01', '1,135,689.01', '145,000.00']
298 1971-11-01 ['681,868.42', '1,009,776.54', '1,157,276.54', '147,500.00']
299 1971-12-01 ['679,016.86', '1,028,910.61', '1,178,910.61', '150,000.00']
300 1972-01-01 ['700,244.88', '1,048,091.25', '1,200,591.25', '152,500.00']

In [12]:
pd.options.display.float_format = "{:,.2f}".format
out_df.tail(36)

,index,month,balance,cum_spend,cum_withdraw,cum_tax,monthly_return(%)
26,266,1969-02-01,"1,514,058.30","414,106.15","479,106.15","65,000.00",-1.00
27,267,1969-03-01,"1,429,232.14","430,912.48","498,412.48","67,500.00",-4.38
28,268,1969-04-01,"1,453,397.38","447,811.92","517,811.92","70,000.00",3.09
29,269,1969-05-01,"1,463,501.41","464,757.91","537,257.91","72,500.00",2.06
30,270,1969-06-01,"1,436,010.82","481,797.02","556,797.02","75,000.00",-0.55
31,271,1969-07-01,"1,349,508.58","498,929.24","576,429.24","77,500.00",-4.72
32,272,1969-08-01,"1,267,324.55","516,108.01","596,108.01","80,000.00",-4.70
33,273,1969-09-01,"1,275,181.14","533,379.89","615,879.89","82,500.00",2.21
34,274,1969-10-01,"1,215,635.81","550,744.88","635,744.88","85,000.00",-3.16
35,275,1969-11-01,"1,255,513.35","568,202.98","655,702.98","87,500.00",5.00
36,276,1969-12-01,"1,185,484.10","585,754.19","675,754.19","90,000.00",-4.05
37,277,1970-01-01,"1,162,589.55","603,398.51","695,898.51","92,500.00",-0.24
38,278,1970-02-01,"1,053,297.79","621,135.94","716,135.94","95,000.00",-7.80
39,279,1970-03-01,"1,080,670.45","638,966.48","736,466.48","97,500.00",4.62
40,280,1970-04-01,"1,064,501.50","656,890.13","756,890.13","100,000.00",0.40
41,281,1970-05-01,"943,998.13","674,860.34","777,360.34","102,500.00",-9.58
42,282,1970-06-01,"882,614.94","692,923.65","797,923.65","105,000.00",-4.42
43,283,1970-07-01,"807,742.23","711,033.52","818,533.52","107,500.00",-6.29
44,284,1970-08-01,"831,112.47","729,189.94","839,189.94","110,000.00",5.59
45,285,1970-09-01,"851,712.29","747,439.48","859,939.48","112,500.00",5.10
46,286,1970-10-01,"865,459.30","765,782.12","880,782.12","115,000.00",4.16
47,287,1970-11-01,"836,410.86","784,217.88","901,717.88","117,500.00",-0.96
48,288,1970-12-01,"854,046.97","802,746.74","922,746.74","120,000.00",4.74
49,289,1971-01-01,"868,015.97","821,322.16","943,822.16","122,500.00",4.21
50,290,1971-02-01,"895,907.90","839,897.58","964,897.58","125,000.00",5.78
51,291,1971-03-01,"880,048.09","858,519.55","986,019.55","127,500.00",0.60
52,292,1971-04-01,"888,896.06","877,188.08","1,007,188.08","130,000.00",3.49
53,293,1971-05-01,"892,698.09","895,949.72","1,028,449.72","132,500.00",2.89
54,294,1971-06-01,"845,276.40","914,804.47","1,049,804.47","135,000.00",-2.99
55,295,1971-07-01,"820,421.74","933,705.77","1,071,205.77","137,500.00",-0.42
56,296,1971-08-01,"768,385.79","952,653.63","1,092,653.63","140,000.00",-3.83
57,297,1971-09-01,"771,097.63","971,648.04","1,114,148.04","142,500.00",3.24
58,298,1971-10-01,"748,497.44","990,689.01","1,135,689.01","145,000.00",-0.14
59,299,1971-11-01,"681,868.42","1,009,776.54","1,157,276.54","147,500.00",-6.20
60,300,1971-12-01,"679,016.86","1,028,910.61","1,178,910.61","150,000.00",2.84
61,301,1972-01-01,"700,244.88","1,048,091.25","1,200,591.25","152,500.00",6.53

##### Move process to a function

In [13]:
def run_trial(
    starting_balance,
    time_til_event,
    duration_of_event,
    start_index,
    monthly_care_amount,
    index_used="^GSPC",
    tax_rate=0.25,
    verbose=False,
    ti=ti,
    mike=mike,
    inflation_adj=1.0,
):
    balance_at_event = (
        starting_balance
        * arrayi[start_index + time_til_event][index_used]
        / arrayi[start_index][index_used]
    )
    start_date = arrayi[start_index]["month"].astype("datetime64[D]")
    event_date = arrayi[start_index + time_til_event]["month"].astype("datetime64[D]")
    sb = "${:,.2f}".format(starting_balance)
    mca = monthly_care_amount * (
        arrayi[time_til_event]["cpi"] / arrayi[start_index]["cpi"]
    )

    if verbose:
        print(
            f"Simulation begins on {start_date}, with initial investment of {sb} and monthly real care cost of {monthly_care_amount}"
        )
        print(f"    Event occurs on {event_date}")
        print(f"    Monthly care at Event", "${:,.2f}".format(mca))
        print("    Balance at event ${:,.2f}".format(balance_at_event))
        ti, mike = ti + time_til_event / 12, mike + time_til_event / 12
        print(f"    Ages at event: Ti {math.floor(ti)}, Mike {math.floor(mike)}")

    # Loop through months to manage payments
    balance = balance_at_event
    cum_spend, cum_withdraw, cum_tax = 0, 0, 0
    out_df = pd.DataFrame(
        {
            "index": [time_til_event],
            "month": [event_date],
            "balance": [balance],
            "cum_spend": [cum_spend],
            "cum_withdraw": [cum_withdraw],
            "cum_tax": [cum_tax],
            "monthly_return(%)": [0.0],
        }
    )

    for m in range(time_til_event, time_til_event + duration_of_event + 1):
        # for m in range(time_til_event, time_til_event + 24 + 1):
        date = arrayi[m]["month"].astype("datetime64[D]")

        # Add inflation to monthly care
        spend = monthly_care_amount * (arrayi[m]["cpi"] / arrayi[start_index]["cpi"])
        tax = monthly_care_amount * tax_rate
        withdraw = spend + tax

        ti += 1 / 12
        mike += 1 / 12
        cum_spend += spend
        cum_withdraw += withdraw
        cum_tax += tax
        balance -= withdraw
        monthly_return = arrayi[m][index_used] / arrayi[m - 1][index_used]
        balance = balance * monthly_return
        fbalance = "${:,.2f}".format(balance)
        formatted = [f"{x:,.2f}" for x in [balance, cum_spend, cum_withdraw, cum_tax]]

        # print(m, date, formatted)

        new_row = {
            "index": m + 1,
            "month": date,
            "balance": balance,
            "cum_spend": cum_spend,
            "cum_withdraw": cum_withdraw,
            "cum_tax": cum_tax,
            "monthly_return(%)": 100 * (monthly_return - 1),
        }
        out_df.loc[len(out_df)] = new_row

    new_row = pd.DataFrame(
        {
            "start_index": [start_index],
            "start_date": [start_date],
            "event_date": [event_date],
            "time_til_event": [time_til_event],
            "mike_age": [math.floor(mike)],
            "inflation_adj": inflation_adj,
            "starting_balance": [starting_balance],
            "index_used": [index_used],
            "duration_of_event": [duration_of_event],
            "starting_care_amount": [monthly_care_amount],
            "cum_spend": [cum_spend],
            "cum_tax": [cum_tax],
            "cum_withdraw": [cum_withdraw],
            "ending_balance": [balance],
        }
    )

    if verbose:
        print("\nEnd of event:")
        print(f"    Ages at end: Ti {math.floor(ti)}, Mike {math.floor(mike)}")
        print(f"    Cum Spend             ", "${:,.2f}".format(cum_spend))
        print(f"    Cum Tax               ", "${:,.2f}".format(cum_tax))
        print(f"    Cum Withdraws         ", "${:,.2f}".format(cum_withdraw))
        print(f"    Remaining balance of   {fbalance}")

    return new_row

In [14]:
starting_balance = 300_000.0
time_til_event = 30 * 12
duration_of_event = 5 * 12
start_index = 0
index_used = "^GSPC"
monthly_care_amount = 7_500.0
tax_rate = 0.25
inflation_adj = 1.1

# Ages at beginning
ti, mike = 54, 53

run_trial(
    starting_balance,
    time_til_event,
    duration_of_event,
    start_index,
    monthly_care_amount,
    index_used="^GSPC",
    tax_rate=0.25,
    verbose=True,
    inflation_adj=1.0,
)
run_trial(
    starting_balance,
    time_til_event,
    duration_of_event,
    start_index,
    monthly_care_amount,
    index_used="^GSPC",
    tax_rate=0.25,
    verbose=True,
    inflation_adj=1.1,
)

Simulation begins on 1947-01-01, with initial investment of $300,000.00 and monthly real care cost of 7500.0
    Event occurs on 1977-01-01
    Monthly care at Event $20,495.81
    Balance at event $2,111,842.13
    Ages at event: Ti 84, Mike 83

End of event:
    Ages at end: Ti 89, Mike 88
    Cum Spend              $1,590,607.54
    Cum Tax                $114,375.00
    Cum Withdraws          $1,704,982.54
    Remaining balance of   $598,803.65
Simulation begins on 1947-01-01, with initial investment of $300,000.00 and monthly real care cost of 7500.0
    Event occurs on 1977-01-01
    Monthly care at Event $20,495.81
    Balance at event $2,111,842.13
    Ages at event: Ti 84, Mike 83

End of event:
    Ages at end: Ti 89, Mike 88
    Cum Spend              $1,590,607.54
    Cum Tax                $114,375.00
    Cum Withdraws          $1,704,982.54
    Remaining balance of   $598,803.65

,start_index,start_date,event_date,time_til_event,mike_age,inflation_adj,starting_balance,index_used,duration_of_event,starting_care_amount,cum_spend,cum_tax,cum_withdraw,ending_balance
0,0,1947-01-01,1977-01-01,360,88,1.10,"300,000.00",^GSPC,60,"7,500.00","1,590,607.54","114,375.00","1,704,982.54","598,803.65"

In [15]:
starting_balance = 300_000.0
event_times = [10 * 12, 15 * 12]
durations = [2 * 12, 5 * 12]
starts = [
    0,
    10,
]
trials = pd.DataFrame()

for time_til_event in event_times:
    for duration_of_event in durations:
        for start_index in starts:
            trial = run_trial(
                starting_balance,
                time_til_event,
                duration_of_event,
                start_index,
                monthly_care_amount,
                index_used="^GSPC",
                tax_rate=0.25,
            )
            trials = pd.concat([trials, trial])
trials.head(10)

,start_index,start_date,event_date,time_til_event,mike_age,inflation_adj,starting_balance,index_used,duration_of_event,starting_care_amount,cum_spend,cum_tax,cum_withdraw,ending_balance
0,0,1947-01-01,1957-01-01,120,55,1.00,"300,000.00",^GSPC,24,"7,500.00","248,931.56","46,875.00","295,806.56","735,318.68"
0,10,1947-11-01,1957-11-01,120,55,1.00,"300,000.00",^GSPC,24,"7,500.00","231,875.54","46,875.00","278,750.54","603,055.26"
0,0,1947-01-01,1957-01-01,120,58,1.00,"300,000.00",^GSPC,60,"7,500.00","620,673.88","114,375.00","735,048.88","415,574.83"
0,10,1947-11-01,1957-11-01,120,58,1.00,"300,000.00",^GSPC,60,"7,500.00","578,147.22","114,375.00","692,522.22","276,760.65"
0,0,1947-01-01,1962-01-01,180,55,1.00,"300,000.00",^GSPC,24,"7,500.00","265,914.80","46,875.00","312,789.80","1,112,339.17"
0,10,1947-11-01,1962-11-01,180,55,1.00,"300,000.00",^GSPC,24,"7,500.00","247,695.14","46,875.00","294,570.14","826,301.53"
0,0,1947-01-01,1962-01-01,180,58,1.00,"300,000.00",^GSPC,60,"7,500.00","664,800.98","114,375.00","779,175.98","740,962.79"
0,10,1947-11-01,1962-11-01,180,58,1.00,"300,000.00",^GSPC,60,"7,500.00","619,250.87","114,375.00","733,625.87","462,194.02"

In [16]:
starting_balance = 300_000.0
monthly_care_amount = 8000.0
event_times = [10, 15, 20, 25, 30]
event_times = [x * 12 for x in event_times]
durations = [2 * 12, 5 * 12, 10 * 12]
starts = range(0, 480, 12)
inflation_adj = 1.0

trials = pd.DataFrame()

for time_til_event in event_times:
    for duration_of_event in durations:
        for start_index in starts:
            trial = run_trial(
                starting_balance,
                time_til_event,
                duration_of_event,
                start_index,
                monthly_care_amount,
                index_used="^GSPC",
                tax_rate=0.25,
            )
            trials = pd.concat([trials, trial])
trials = trials.reset_index()
trials.head()

,index,start_index,start_date,event_date,time_til_event,mike_age,inflation_adj,starting_balance,index_used,duration_of_event,starting_care_amount,cum_spend,cum_tax,cum_withdraw,ending_balance
0,0,0,1947-01-01,1957-01-01,120,55,1.00,"300,000.00",^GSPC,24,"8,000.00","265,527.00","50,000.00","315,527.00","711,043.52"
1,0,12,1948-01-01,1958-01-01,120,55,1.00,"300,000.00",^GSPC,24,"8,000.00","240,858.11","50,000.00","290,858.11","592,959.17"
2,0,24,1949-01-01,1959-01-01,120,55,1.00,"300,000.00",^GSPC,24,"8,000.00","237,547.69","50,000.00","287,547.69","987,436.44"
3,0,36,1950-01-01,1960-01-01,120,55,1.00,"300,000.00",^GSPC,24,"8,000.00","242,599.74","50,000.00","292,599.74","940,587.92"
4,0,48,1951-01-01,1961-01-01,120,55,1.00,"300,000.00",^GSPC,24,"8,000.00","224,724.98","50,000.00","274,724.98","664,440.39"

In [17]:
trials.tail()

,index,start_index,start_date,event_date,time_til_event,mike_age,inflation_adj,starting_balance,index_used,duration_of_event,starting_care_amount,cum_spend,cum_tax,cum_withdraw,ending_balance
595,0,420,1982-01-01,2012-01-01,360,63,1.00,"300,000.00",^GSPC,120,"8,000.00","913,610.17","242,000.00","1,155,610.17","5,376,163.51"
596,0,432,1983-01-01,2013-01-01,360,63,1.00,"300,000.00",^GSPC,120,"8,000.00","880,947.91","242,000.00","1,122,947.91","5,555,930.70"
597,0,444,1984-01-01,2014-01-01,360,63,1.00,"300,000.00",^GSPC,120,"8,000.00","844,709.11","242,000.00","1,086,709.11","6,052,474.73"
598,0,456,1985-01-01,2015-01-01,360,63,1.00,"300,000.00",^GSPC,120,"8,000.00","815,939.45","242,000.00","1,057,939.45","7,026,990.75"
599,0,468,1986-01-01,2016-01-01,360,63,1.00,"300,000.00",^GSPC,120,"8,000.00","784,757.05","242,000.00","1,026,757.05","5,032,831.97"

In [18]:
# Write to an Excel file with multiple tabs
trials.to_excel("trials.xlsx")

In [19]:
event_times = [10, 15, 20, 25, 30]
event_times = [x * 12 for x in event_times]
print(event_times)

[120, 180, 240, 300, 360]

In [20]:
starting_balance = 450_000.0
monthly_care_amount = 8000.0
durations = [5 * 12]
inflation_adj = 1.0

event_times = [x * 12 for x in [10, 15, 20, 25, 30]]
event_times = range(0, 12 * 30, 24)
starts = range(0, 600, 24)

trials = pd.DataFrame()

for time_til_event in event_times:
    for duration_of_event in durations:
        for start_index in starts:
            trial = run_trial(
                starting_balance,
                time_til_event,
                duration_of_event,
                start_index,
                monthly_care_amount,
                index_used="^GSPC",
                tax_rate=0.20,
            )
            trials = pd.concat([trials, trial])
trials = trials.reset_index()

# Create pivot table
tmp = trials.copy(deep=True)
tmp["time_til_event"] = round(tmp["time_til_event"] / 12)
tmp["ending_balance"] = tmp["ending_balance"] / 1000

pivot_df = pd.pivot_table(
    tmp, index="start_date", columns="time_til_event", values="ending_balance"
)
v = np.nanmax(np.abs(pivot_df.values))

styled = pivot_df.style.background_gradient(cmap="RdYlGn", vmin=-v, vmax=v).format(
    "{:,.0f}"
)
styled

In [22]:
starting_balance = 350_000.0
monthly_care_amount = 8000.0
durations = [5 * 12]
inflation_adj = 1.0

event_times = [x * 12 for x in [10, 15, 20, 25, 30]]
event_times = range(0, 12 * 30, 24)
starts = range(0, 600, 24)

trials = pd.DataFrame()

for time_til_event in event_times:
    for duration_of_event in durations:
        for start_index in starts:
            trial = run_trial(
                starting_balance,
                time_til_event,
                duration_of_event,
                start_index,
                monthly_care_amount,
                index_used="^GSPC",
                tax_rate=0.25,
            )
            trials = pd.concat([trials, trial])
trials = trials.reset_index()

# Create pivot table
tmp = trials.copy(deep=True)
tmp["time_til_event"] = round(tmp["time_til_event"] / 12)
tmp["ending_balance"] = tmp["ending_balance"] / 1000

pivot_df = pd.pivot_table(
    tmp, index="start_date", columns="time_til_event", values="ending_balance"
)
v = np.nanmax(np.abs(pivot_df.values))

styled = pivot_df.style.background_gradient(cmap="RdYlGn", vmin=-v, vmax=v).format(
    "{:,.0f}"
)

styled